-- 05-borrow-records.sql
-- HWrequirement:
-- BorrowRecord table, RLS policies, and max 5-day borrowing logic.

create table if not exists public.borrow_records (
    id bigint generated by default as identity primary key,

    user_id uuid not null references auth.users(id) on delete cascade,
    book_id bigint not null references public.books(id) on delete cascade,

    borrowed_at timestamp with time zone not null default now(),
    due_at timestamp with time zone not null,
    returned_at timestamp with time zone,

    status text not null default 'active'
        check (status in ('active', 'returned', 'late')),

    created_at timestamp with time zone not null default now(),

    constraint borrow_records_max_5_days_check
        check (
            due_at > borrowed_at
            and due_at <= borrowed_at + interval '5 days'
        )
);

alter table public.borrow_records enable row level security;

drop policy if exists "Users can view own borrow records"
on public.borrow_records;

create policy "Users can view own borrow records"
on public.borrow_records
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own borrow records"
on public.borrow_records;

create policy "Users can create own borrow records"
on public.borrow_records
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own borrow records"
on public.borrow_records;

create policy "Users can update own borrow records"
on public.borrow_records
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- One student cannot actively borrow the same book twice.
create unique index if not exists unique_active_borrow_record_per_user_book
on public.borrow_records(user_id, book_id)
where status = 'active' and returned_at is null;

-- Helpful indexes for listing records.
create index if not exists borrow_records_user_id_idx
on public.borrow_records(user_id);

create index if not exists borrow_records_book_id_idx
on public.borrow_records(book_id);

-- Safe borrow function for homework version.
-- It checks login, max 5 days, stock, duplicate active borrow, then creates BorrowRecord.

create or replace function public.borrow_book_with_record(
    p_book_id bigint,
    p_days int
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
    v_user_id uuid := auth.uid();
    v_available_count int;
begin
    if v_user_id is null then
        raise exception 'User must be logged in.';
    end if;

    if p_days is null or p_days < 1 or p_days > 5 then
        raise exception 'Borrow duration must be between 1 and 5 days.';
    end if;

    if exists (
        select 1
        from public.borrow_records
        where user_id = v_user_id
          and book_id = p_book_id
          and status = 'active'
          and returned_at is null
    ) then
        raise exception 'You already have an active borrow record for this book.';
    end if;

    select available_count
    into v_available_count
    from public.books
    where id = p_book_id
    for update;

    if v_available_count is null then
        raise exception 'Book not found.';
    end if;

    if v_available_count <= 0 then
        raise exception 'This book is out of stock.';
    end if;

    update public.books
    set available_count = available_count - 1
    where id = p_book_id;

    insert into public.borrow_records (
        user_id,
        book_id,
        borrowed_at,
        due_at,
        status
    )
    values (
        v_user_id,
        p_book_id,
        now(),
        now() + (p_days || ' days')::interval,
        'active'
    );

    return 'Book borrowed successfully.';
end;
$$;

grant execute on function public.borrow_book_with_record(bigint, int)
to authenticated;